config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :events do
    resources :tickets
    resources :invitations, only: [:create]
  end
  resources :users do
    get "invitations", on: :member
    get "sent_invitations", on: :member
  end
  resources :invitations, only: [] do
    member do
      put 'accept'
      delete 'reject'
    end
  end


  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :tickets, dependent: :destroy
  has_many :attendees, through: :tickets, source: :attendee
  has_many :invitations
  has_many :invitations_attendees, through: :invitations, source: :recipient

  scope :past, -> {where('date < ?', Time.now)}
  scope :future, -> {where('date >= ?', Time.now)}
  validates :title, presence: true
  validates :description, presence: true
  validates :date, presence: true
  validates :location, presence: true
  validates :private, inclusion: { in: [true, false]}

end

app/models/invitation.rb
class Invitation < ApplicationRecord
  belongs_to :sender, class_name: "User"
  belongs_to :recipient, class_name: "User", primary_key: "email", foreign_key: "recipient_email"
  belongs_to :event

  validates :sender_id, presence: true
  validates :recipient_email, presence: true
  validates :event_id, presence: true
end

app/models/ticket.rb
class Ticket < ApplicationRecord
  belongs_to :event
  belongs_to :attendee, class_name: "User"

  validates :email, presence: true
  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :events, foreign_key: "creator_id"
  has_many :tickets, foreign_key: "attendee_id"
  has_many :attended_events, through: :tickets, source: :event
  has_many :sent_invitations, foreign_key: "sender_id", class_name: "Invitation"
  has_many :received_invitations, foreign_key: "recipient_email", class_name: "Invitation", primary_key: "email"
  has_many :invited_events, through: :received_invitations, source: :event
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show] 
  before_action :set_event, except: [:index, :new, :create]

  def index
    if current_user
      @events = Event.where(private: false)
        .or(current_user.events.where(private: true)).includes(:creator).limit(20).order(created_at: :desc)
      @invited_private_events = current_user.invited_events.distinct.limit(20).order(created_at: :desc)
      else
      @events = Event.where(private: false).includes(:creator).limit(20).order(created_at: :desc)
    end
  end

  def show
    @attendees_name = @event.tickets.pluck(:name)
  end

  def new
    @event = Event.new
  end

  def create
    @user = current_user  
    @event = @user.events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    if @event.creator == current_user
      render :edit
    else
      redirect_to root_path
    end
  end

  def update
    if @event.creator == current_user
      if @event.update(event_params)
        redirect_to @event
      else
        render :edit, status: :unprocessable_entity
      end
    else
      redirect_to root_path
    end
  end

  def destroy
    if @event.creator == current_user
      @event.destroy
    end
    redirect_to root_path
  end

  private

  def event_params 
    params.require(:event).permit(:title, :description, :date, :location, :private)
  end

  def set_event
    @event = Event.find(params[:id])
  rescue ActiveRecord::RecordNotFound
    redirect_to root_path
  end

end

app/controllers/invitations_controller.rb
class InvitationsController < ApplicationController
  before_action :authenticate_user!

  def create
    if params[:invitation][:sender_id] = current_user.id
      @event = Event.find(params[:event_id])  
      @invitation = @event.invitations.build(invitation_params)

      # Try to find the recipient by email
      recipient = User.find_by(email: params[:invitation][:recipient_email])

      if @invitation.save
        redirect_to @event, notice: 'Invitation was successfully sent.'
      else
        flash[:error] = @invitation.errors.full_messages.join(", ")
        redirect_to @event
      end
    else
      redirect_to @event
    end
  end

  def accept
    @invitation = Invitation.find(params[:id])
    @invitation.accepted = true

    if @invitation.save
      flash[:notice] = 'Invitation accepted!'
    else
      flash[:error] = "Failed to accept invitation."
    end

    redirect_to current_user
  end

  def reject
    @invitation = Invitation.find(params[:id])
    @invitation.destroy

    flash[:notice] = 'Invitation rejected!'
    redirect_to current_user
  end

  private

  def invitation_params
    params.require(:invitation).permit(:recipient_email, :sender_id, :event_id)
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!

  def create
    if params[:ticket][:attendee_id] = current_user.id
      @event = Event.find(params[:event_id])  
      @ticket = @event.tickets.build(ticket_params)
      if @ticket.save
        redirect_to @event, notice: 'Ticket was successfully created.'
      else
        flash[:error] = @ticket.errors.full_messages.join(", ")
        redirect_to @event
      end
    else
      redirect_to @event
    end
  end

  def destroy
    @ticket = Ticket.find(params[:id])
    if @ticket.attendee == current_user
      @ticket.destroy
    end
    redirect_to root_path
  end

  private

  def ticket_params
    params.require(:ticket).permit(:event_id, :attendee_id, :name, :email)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  def show
    @user = current_user
    @events = @user.events.limit(20).order(created_at: :desc)
    @attended_events = @user.attended_events.limit(20).order(created_at: :desc)
  end

  def invitations
    @user = current_user
    @accepted_invitations = @user.received_invitations.where('accepted = ?', true).limit(20).order(created_at: :desc)
    @unread_invitations = @user.received_invitations.where(accepted: nil).limit(20).order(created_at: :desc)
  end

  def sent_invitations
    @user = current_user
    @accepted_sent_invitations = @user.sent_invitations.where('accepted = ?', true).limit(20).order(created_at: :desc)
    @unread_sent_invitations = @user.sent_invitations.where(accepted: nil).limit(20).order(created_at: :desc)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/invitations_helper.rb
module InvitationsHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form_event.html.erb
<%= form_with model: @event do |form| %>
  <% if @event.errors.any?%>
    <div id = "error_explanation">
      <h3><%= pluralize(@event.errors.count, "error")%> occurred:</h3>
      <ul>
        <% @event.errors.full_messages.each do |msg|%>
        <li><%= msg%> </li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div><%= form.label :title %></div>
  <div><%= form.text_area :title %></div>
  <div><%= form.label :description %></div>
  <div><%= form.text_area :description %></div>
  <div><%= form.label :date %></div>
  <div><%= form.date_field :date %></div>
  <div><%= form.label :location %></div>
  <div><%= form.text_area :location %></div>
  <div><%= form.label :private %></div>
  <div><%= form.collection_radio_buttons :private, [[true, "Private"], [false, "Public"]], :first, :last %></div>
  <div><%= form.submit %></div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit your event</h1>
<%= render "form_event" %>

app/views/events/index.html.erb
<% future_events = @events.future
past_events = @events.past %>
<% if future_events.any? %>
  <h1>Upcoming Public Events</h1>
  <ul>
    <% future_events.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if past_events.any? %>
  <h1>Ended Public Events</h1>
  <ul>
    <% past_events.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% if @invited_private_events %>
  <% future_private_events = @invited_private_events.where('date > ?', Time.now)
  past_private_events = @invited_private_events.where('date < ?', Time.now) %>
  <% if future_private_events.any? %>
    <h1>Upcoming Private Events</h1>
    <ul>
      <% future_private_events.each do |event| %>
        <li>
          <%= link_to event.title, event_path(event) %>
        </li>
      <% end %>
    </ul>
  <% end %>

  <% if past_private_events.any? %>
    <h1>Ended Private Events</h1>
    <ul>
      <% past_private_events.each do |event| %>
        <li>
          <%= link_to event.title, event_path(event) %>
        </li>
      <% end %>
    </ul>
  <% end %>
<% end %>

app/views/events/new.html.erb
<%= render "form_event" %>

app/views/events/show.html.erb
<% if user_signed_in? && @event.creator == current_user %>
  <%= link_to "Edit Event", edit_event_path %>
  <%= link_to "Delete Event", @event, data: {
    turbo_method: :delete,
    turbo_confirm: "Are you sure?"
  }%>
<% end %>
<h1><%= @event.title %></h1>
<p>
<div>About this event: </div>
<div><%= @event.description %></div>
</p>
<p>
<div>Time: </div>
<div><%= @event.date %></div>
</p>
<p>
<div>Location: </div>
<div><%= @event.location %></div>
</p>

<% if current_user != @event.creator %>
  <h2>Book Your Ticket Now</h2>
  <%= render "tickets/form"%>
<% end %>

<% if current_user == @event.creator and @event.private %>
  <h1>Send private invitation to other users:</h1>
  <%= render "invitations/form" %>
<% end %>

<% if @event.tickets.count > 0 %>
  <h2>List of current attendees</h2>

  <ul>
  <% @attendees_name.each do |attendee_name| %>
    <li> <%= attendee_name %> </li>
  <% end %>
  </ul>
<% end %>

app/views/invitations/_form.html.erb
<%= form_with model: [@event, @event.invitations.build] do |form| %>
  <%= form.label :recipient_email %>
  <%= form.text_field :recipient_email %>
  <%= form.hidden_field :sender_id, value: current_user.id %>
  <%= form.submit %>
  <% if flash[:error].present? %>
    <div class="error">
      <%= flash[:error] %>
    </div>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PrivateEvents</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    
    <%= link_to "Home", root_path %>
    <% if user_signed_in? %>
      <%= link_to "My Events", user_path(current_user) %>
      <%= link_to "Inbox", invitations_user_path(current_user) %>
      <%= link_to "My sent invitations", sent_invitations_user_path(current_user) %>
      <%= link_to "Profile", edit_user_registration_path %>      
      <%= link_to "Log out", destroy_user_session_path, method: :delete, data: { turbo_method: :delete } %>
    <% else %>
      <%= link_to "Sign in", new_user_session_path %>
    <% end %>
    <hr>
    
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to "Add Event", new_event_path %>
    <%= yield %>
  </body>
</html>

app/views/tickets/_form.html.erb
<%= form_with model: [@event, @event.tickets.build] do |form| %>
  <p>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </p>
  <p>
    <%= form.label :email %>
    <%= form.text_field :email %>
    <% if user_signed_in? %>
      <%= form.hidden_field :attendee_id, value: current_user.id %>
    <% end %>
  </p>
  <%= form.submit "Book Ticket" %>
  <% if flash[:error].present? %>
    <div class="error">
      <%= flash[:error] %>
    </div>
  <% end %>
<% end %>

app/views/users/invitations.html.erb
<% if @unread_invitations.any? %>
  <h1>Your awaiting invitations</h1>
  <% @unread_invitations.each do |invitation| %>
    <div>
      <p> Event: <%= link_to invitation.event.title, event_path(invitation.event) %> </p>
      <p> Sender: <%= invitation.sender.email %> </p>
      <p>
        <%= link_to "Reject Invitation", reject_invitation_path(invitation), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
        <%= link_to "Accept Invitation", accept_invitation_path(invitation), data: {
          turbo_method: :put,
          turbo_confirm: "Are you sure?"
        } %>
      </p>
    </div>
    <hr>
  <% end %>
<% end %>

<% if @accepted_invitations.any? %>
  <h1>Your accepted invitations</h1>

  <% @accepted_invitations.each do |invitation| %>
    <div>
      <p> Event: <%= link_to invitation.event.title, event_path(invitation.event) %> </p>
      <p> Sender: <%= invitation.sender.email %> </p>
      <p>
        <%= link_to "Reject Invitation", reject_invitation_path(invitation), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
        <%= link_to "Go to event", event_path(invitation.event) %>
      </p>
    </div>
    <hr>
  <% end %>
<% end %>

app/views/users/sent_invitations.html.erb
<% if @unread_sent_invitations.any? %>
  <h1>Your not-been-accepted sent invitations</h1>

  <% @unread_sent_invitations.each do |invitation| %>
    <div>
      <p> Event: <%= link_to invitation.event.title, event_path(invitation.event) %> </p>
      <p> Recipient: <%= invitation.recipient_email %> </p>
      <p>
        <%= link_to "Remove Invitation", reject_invitation_path(invitation), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        } %>
      </p>
    </div>
    <hr>
  <% end %>
<% end %>

<% if @accepted_sent_invitations.any? %>
  <h1>Your been-accepted sent invitations</h1>

  <% @accepted_sent_invitations.each do |invitation| %>
    <div>
      <p> Event: <%= link_to invitation.event.title, event_path(invitation.event) %> </p>
      <p> Recipient: <%= invitation.recipient_email %> </p>
    </div>
    <hr>
  <% end %>
<% end %>

app/views/users/show.html.erb
<% if @events.empty? && @attended_events.empty? %>
  <p>You events space is currently empty</p>
<% end %>

<% if @events.any? %>
  <h1>My created events </h1>

  <ul>
    <% @events.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
<% end %>

<% future_events = @attended_events.where('date >= ?', Time.now) %>
<% if future_events.any? %>
  <h1>Upcoming booked events </h1>
  <ul>
    <% future_events.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
        <br>
        <%= link_to "Delete Ticket", event_ticket_path(event, event.tickets.where(attendee_id: @user.id).first), data: {
          turbo_method: :delete,
          turbo_confirm: "Are you sure?"
        }%>
      </li>
    <% end %>
  </ul>
<% end %>

<% past_events = @attended_events.where('date < ?', Time.now) %>
<% if past_events.any? %>
  <h1>Past booked events</h1>
  <ul>
    <% past_events.each do |event| %>
      <li>
        <%= link_to event.title, event_path(event) %>
      </li>
    <% end %>
  </ul>
<% end %>